version: "3.7"

services:
  database_quake:
    image: postgres
    container_name: course_spring_boot
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=course_spring_boot
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local